<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;

class RolePermissionSeeder extends Seeder
{
    public function run(): void
    {
        app()[\Spatie\Permission\PermissionRegistrar::class]->forgetCachedPermissions();

        $permissions = [

            // SYSTEM
            'system.admin',

            // GENERAL MODULE
            'my-inventories.view',
            'my-iis-inventories.view',

            // PROCUREMENT
            'procurement.view',
            'procurement.create',
            'procurement.update',
            'procurement.submit',
            'procurement.verified',
            'procurement.approve',

            // MASTER DATA
            'warehouse.view',
            'warehouse.create',
            'warehouse.update',
            'warehouse.delete',
            'building.view',
            'building.create',
            'building.update',
            'building.delete',
            'transaction_type.view',
            'transaction_type.create',
            'transaction_type.update',
            'transaction_type.delete',
            'stock_code.view',
            'stock_code.create',
            'stock_code.update',
            'stock_code.delete',
            'category.view',
            'category.create',
            'category.update',
            'category.delete',
            'depreciation_group.view',
            'depreciation_group.create',
            'depreciation_group.update',
            'depreciation_group.delete',
            'uom.view',
            'uom.create',
            'uom.update',
            'uom.delete',
            'item.view',
            'item.create',
            'item.update',
            'item.delete',
            'supplier.view',
            'supplier.create',
            'supplier.update',
            'supplier.delete',
            'unit.view',
            'unit.create',
            'unit.update',
            'unit.delete',
            'room.view',
            'room.create',
            'room.update',
            'room.delete',

            // IIS Module
            'iis.inventories-list.view',
            'iis.inventories-list.create',
            'iis.inventories-list.update',
            'iis.inventories-list.delete',
            'iis.inventories-list.qr.print',
            'iis.inventories-list.maintenance',
            'iis.alkes-list.view',
            'iis.alkes-list.create',
            'iis.alkes-list.update',
            'iis.alkes-list.delete',
            'iis.alkes-list.qr.print',
            'iis.alkes-list.maintenance',
            'iis.ac-list.view',
            'iis.ac-list.create',
            'iis.ac-list.update',
            'iis.ac-list.delete',
            'iis.ac-list.qr.print',
            'iis.ac-list.maintenance',
            'iis.items.view',
            'iis.items.create',
            'iis.items.update',
            'iis.items.delete',
            'iis.categories-list.view',
            'iis.categories-list.create',
            'iis.categories-list.update',
            'iis.categories-list.delete',
            'iis.qrcode-handover.view',
            'iis.qrcode-handover.view_all',
            'iis.qrcode-handover.create',
            'iis.qrcode-handover.update',
            'iis.qrcode-handover.delete',
            'iis.qrcode-handover.submit',
            'iis.qrcode-handover.approve',
            'iis.qrcode-handover.verify',
            'iis.qrcode-handover.reject',
            'iis.mutation.view',
            'iis.mutation.view_all',
            'iis.mutation.create',
            'iis.mutation.update',
            'iis.mutation.delete',
            'iis.mutation.submit',
            'iis.mutation.verify',
            'iis.mutation.approve',
            'iis.mutation.reject',
            'iis.distribution.view',
            'iis.distribution.view_all',
            'iis.distribution.create',
            'iis.distribution.update',
            'iis.distribution.delete',
            'iis.distribution.submit',
            'iis.distribution.verify',
            'iis.distribution.reject',
            'iis.return.view',
            'iis.return.view_all',
            'iis.return.create',
            'iis.return.update',
            'iis.return.delete',
            'iis.return.submit',
            'iis.return.verify',
            'iis.return.reject',
            'iis.borrow.view',
            'iis.borrow.view_all',
            'iis.borrow.create',
            'iis.borrow.update',
            'iis.borrow.delete',
            'iis.borrow.submit',
            'iis.borrow.verify',
            'iis.borrow.reject',
            'iis.borrow-return.view',
            'iis.borrow-return.view_all',
            'iis.borrow-return.create',
            'iis.borrow-return.update',
            'iis.borrow-return.delete',
            'iis.borrow-return.submit',
            'iis.borrow-return.verify',
            'iis.borrow-return.reject',
            'iis.internal-maintenance.view',
            'iis.internal-maintenance.create',
            'iis.internal-maintenance.update',
            'iis.internal-maintenance.delete',
            'iis.internal-maintenance.verify',
            'iis.internal-maintenance.reject',
            'iis.external-maintenance.view',
            'iis.external-maintenance.create',
            'iis.external-maintenance.update',
            'iis.external-maintenance.delete',
            'iis.external-maintenance.verify',
            'iis.external-maintenance.reject',
            'iis.usage.view',
            'iis.usage.create',
            'iis.usage.update',
            'iis.usage.delete',
            'iis.usage.verify',
            'iis.usage.reject',
            'iis.usage.view',
            'iis.usage.create',
            'iis.usage.update',
            'iis.usage.delete',
            'iis.usage.verify',
            'iis.usage.reject',
            'iis.disposal.view',
            'iis.disposal.create',
            'iis.disposal.update',
            'iis.disposal.delete',
            'iis.disposal.submit',
            'iis.disposal.verify',
            'iis.disposal.reject',

            // RE-qrcode / RE-PRINT
            'iis.inventory.print.unlimited',
            'iis.alkes.print.unlimited',
            'iis.ac.print.unlimited',
        ];

        foreach ($permissions as $perm) {
            Permission::firstOrCreate(['name' => $perm]);
        }

        $roles = [
            'superadmin' => Permission::all(),

            'administrator' => [
                'procurement.view',
                'procurement.create',
                'procurement.update',
                'procurement.submit',
                'procurement.verified',
                'procurement.approve',

                // MASTER DATA
                'warehouse.view',
                'warehouse.create',
                'warehouse.update',
                'warehouse.delete',
                'building.view',
                'building.create',
                'building.update',
                'building.delete',
                'transaction_type.view',
                'transaction_type.create',
                'transaction_type.update',
                'transaction_type.delete',
                'stock_code.view',
                'stock_code.create',
                'stock_code.update',
                'stock_code.delete',
                'category.view',
                'category.create',
                'category.update',
                'category.delete',
                'depreciation_group.view',
                'depreciation_group.create',
                'depreciation_group.update',
                'depreciation_group.delete',
                'uom.view',
                'uom.create',
                'uom.update',
                'uom.delete',
                'item.view',
                'item.create',
                'item.update',
                'item.delete',
                'supplier.view',
                'supplier.create',
                'supplier.update',
                'supplier.delete',
                'unit.view',
                'unit.create',
                'unit.update',
                'unit.delete',
                'room.view',
                'room.create',
                'room.update',
                'room.delete',

                // IIS Module
                'iis.inventories-list.view',
                'iis.inventories-list.create',
                'iis.inventories-list.update',
                'iis.inventories-list.delete',
                'iis.inventories-list.qr.print',
                'iis.alkes-list.view',
                'iis.alkes-list.create',
                'iis.alkes-list.update',
                'iis.alkes-list.delete',
                'iis.alkes-list.qr.print',
                'iis.items.view',
                'iis.items.create',
                'iis.items.update',
                'iis.items.delete',
                'iis.categories-list.view',
                'iis.categories-list.create',
                'iis.categories-list.update',
                'iis.categories-list.delete',
                'iis.qrcode-handover.view',
                'iis.mutation.view',
                'iis.mutation.view_all',
                'iis.mutation.create',
                'iis.mutation.update',
                'iis.mutation.delete',
                'iis.distribution.view',
                'iis.distribution.view_all',
                'iis.distribution.create',
                'iis.distribution.update',
                'iis.distribution.delete',
                'iis.distribution.submit',
                'iis.distribution.verify',
                'iis.distribution.reject',
                'iis.return.view',
                'iis.return.view_all',
                'iis.return.create',
                'iis.return.update',
                'iis.return.delete',
                'iis.return.submit',
                'iis.return.reject',
                'iis.borrow.view',
                'iis.borrow.view_all',
                'iis.borrow.create',
                'iis.borrow.update',
                'iis.borrow.delete',
                'iis.borrow.submit',
                'iis.borrow.verify',
                'iis.borrow.reject',
                'iis.borrow-return.view',
                'iis.borrow-return.view_all',
                'iis.borrow-return.create',
                'iis.borrow-return.update',
                'iis.borrow-return.delete',
                'iis.borrow-return.submit',
                'iis.borrow-return.verify',
                'iis.borrow-return.reject',

                // RE-qrcode / RE-PRINT
                'iis.inventory.print.unlimited',
                'iis.alkes.print.unlimited',
            ],

            'purchasing_officer' => [
                'procurement.view',
                'procurement.create',
                'procurement.update',
                'procurement.submit',

                // MASTER DATA
                'warehouse.view',
                'transaction_type.view',
                'stock_code.view',
                'category.view',
                'depreciation_group.view',
                'uom.view',
                'item.view',
                'supplier.view',
                'unit.view',
                'room.view',
            ],

            'finance_administrator' => [
                'procurement.view',
                'procurement.verified',

                // MASTER DATA
                'warehouse.view',
                'warehouse.create',
                'warehouse.update',
                'warehouse.delete',
                'building.view',
                'building.create',
                'building.update',
                'building.delete',
                'transaction_type.view',
                'transaction_type.create',
                'transaction_type.update',
                'transaction_type.delete',
                'stock_code.view',
                'stock_code.create',
                'stock_code.update',
                'stock_code.delete',
                'category.view',
                'category.create',
                'category.update',
                'category.delete',
                'depreciation_group.view',
                'depreciation_group.create',
                'depreciation_group.update',
                'depreciation_group.delete',
                'uom.view',
                'uom.create',
                'uom.update',
                'uom.delete',
                'item.view',
                'item.create',
                'item.update',
                'item.delete',
                'supplier.view',
                'supplier.create',
                'supplier.update',
                'supplier.delete',
                'unit.view',
                'unit.create',
                'unit.update',
                'unit.delete',
                'room.view',
                'room.create',
                'room.update',
                'room.delete',

                // IIS Module
                'iis.inventories-list.view',
                'iis.inventories-list.create',
                'iis.inventories-list.update',
                'iis.inventories-list.delete',
                'iis.inventories-list.qr.print',
                'iis.inventories-list.maintenance',
                'iis.alkes-list.view',
                'iis.alkes-list.create',
                'iis.alkes-list.update',
                'iis.alkes-list.delete',
                'iis.alkes-list.qr.print',
                'iis.alkes-list.maintenance',
                'iis.items.view',
                'iis.items.create',
                'iis.items.update',
                'iis.items.delete',
                'iis.categories-list.view',
                'iis.categories-list.create',
                'iis.categories-list.update',
                'iis.categories-list.delete',
                'iis.qrcode-handover.view',
                'iis.disposal.view',
                'iis.disposal.create',
                'iis.disposal.update',
                'iis.disposal.delete',
                'iis.disposal.submit',
                'iis.disposal.verify',
                'iis.disposal.reject',

                // RE-qrcode / RE-PRINT
                'iis.inventory.print.unlimited',
                'iis.alkes.print.unlimited',
            ],

            'warehouse_administrator' => [
                // MASTER DATA
                'item.view',

                // IIS Module
                'iis.inventories-list.view',
                'iis.inventories-list.create',
                'iis.inventories-list.update',
                'iis.inventories-list.delete',
                'iis.inventories-list.qr.print',
                'iis.alkes-list.view',
                'iis.alkes-list.create',
                'iis.alkes-list.update',
                'iis.alkes-list.delete',
                'iis.alkes-list.qr.print',
                'iis.ac-list.view',
                'iis.ac-list.create',
                'iis.ac-list.update',
                'iis.ac-list.delete',
                'iis.ac-list.qr.print',
                'iis.items.view',
                'iis.qrcode-handover.view',
                'iis.qrcode-handover.view_all',
                'iis.qrcode-handover.create',
                'iis.qrcode-handover.update',
                'iis.qrcode-handover.delete',
                'iis.qrcode-handover.submit',
                'iis.distribution.view',
                'iis.distribution.view_all',
                'iis.distribution.create',
                'iis.distribution.update',
                'iis.distribution.delete',
                'iis.distribution.submit',
                'iis.return.view',
                'iis.return.view_all',
                'iis.return.verify',
                'iis.return.reject',
                'iis.borrow.view',
                'iis.borrow.view_all',
                'iis.borrow.create',
                'iis.borrow.update',
                'iis.borrow.delete',
                'iis.borrow.submit',
                'iis.borrow-return.view',
                'iis.borrow-return.view_all',
                'iis.borrow-return.verify',
                'iis.borrow-return.reject',

            ],

            'staff' => [
                'my-inventories.view',
                'my-iis-inventories.view',
                'iis.qrcode-handover.view',
                'iis.qrcode-handover.approve',
                'iis.qrcode-handover.verify',
                'iis.qrcode-handover.reject',
                'iis.mutation.view',
                'iis.mutation.create',
                'iis.mutation.update',
                'iis.mutation.delete',
                'iis.mutation.submit',
                'iis.mutation.approve',
                'iis.mutation.verify',
                'iis.mutation.reject',
                'iis.distribution.view',
                'iis.distribution.verify',
                'iis.distribution.reject',
                'iis.return.view',
                'iis.return.create',
                'iis.return.update',
                'iis.return.submit',
            ],

            'staff-external' => [
                'iis.borrow.view',
                'iis.borrow.verify',
                'iis.borrow.reject',
                'iis.borrow-return.view',
                'iis.borrow-return.create',
                'iis.borrow-return.update',
                'iis.borrow-return.submit',
            ],
        ];

        foreach ($roles as $role => $perms) {
            $r = Role::firstOrCreate(['name' => $role]);
            $r->syncPermissions($perms);
        }
    }
}
